User story 1
julianchahine/lean-coffee pull request #1
Opened 2021-09-30 13:40 UTC by julianchahine

2021-09-30 14:09 UTC, StefanBehring requested changes
Please look at the suggestions I made

2021-09-30 14:09 UTC, StefanBehring commented on client/src/components/Header.js
> +import './css/header.css'
Da wir mit styled components arbeiten wollen, kann auf den Import hier verzichtet werden

2021-09-30 14:09 UTC, StefanBehring commented on client/src/components/css/main.css
> +
Diese stylings auch direkt in die styled components schieben

2021-09-30 14:09 UTC, timurbuch commented on client/src/components/Content.js
> +  @media screen and (max-width: 768px) {
Nice use of calc() 👌🏽

2021-09-30 14:09 UTC, timurbuch commented on client/src/App.js
> +      <Header />
While the structure is nice, it seems like you did a lot more than asked in userstory 1 😉

2021-09-30 14:09 UTC, timurbuch commented on client/src/components/Content.spec.js
> +import { render, screen } from '@testing-library/react'
Looks good 👍🏽

2021-09-30 14:12 UTC, julianchahine commented on client/src/components/Content.js
> +        <StyledCard className="card" key={card.author}>
Thx.

2021-09-30 14:12 UTC, julianchahine commented on client/src/components/Header.js
> +import './css/header.css'
Okay, stellen es um

2021-09-30 14:13 UTC, julianchahine commented on client/src/App.js
> +      <Header />
Haha, dachten en kleiner Header ist ganz n1 xD

2021-09-30 14:27 UTC, merged

2021-10-01 07:20 UTC, macfrei reviewed
Good job, added a few comments you might want to consider!

2021-10-01 07:20 UTC, macfrei commented on client/src/components/Content.js
> +  ]
This data should be defined outside of your `Content` component, for example above the function declaration. Right now the data is rendered every time you are doing a reload and that is not really necessary.

2021-10-01 07:20 UTC, macfrei commented on client/src/components/Create.js
> +
This should not be part of the first user story!

2021-10-01 07:20 UTC, macfrei commented on client/src/index.css
> +}
Please remove the `index.css` file and create a `GlobalStyle.js` instead.

2021-10-01 07:20 UTC, macfrei commented on client/src/components/Header.js
> +import styled from 'styled-components'
`import styled from 'styled-components/macro'`

2021-10-01 07:20 UTC, macfrei commented on client/src/components/Content.js
> +        <StyledCard key={nanoid}>
The key should never be created when rendering it! This will lead to really bad behaviour of your components. We can talk about it later.

2021-10-01 07:20 UTC, macfrei commented on client/src/components/Content.js
> +          <div className="card__author">Author: {card.author}</div>
Please remove the `className`